# -*- mode: ruby -*-
# vi: set ft=ruby :
# Sergey Pimenov

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.define "static" do |static|
    
     static.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

     static.vm.network "private_network", ip: "192.168.1.80"
     
     static.vm.provider "virtualbox" do |vb|
    	vb.name = "01-demosite-static"
        vb.memory = "512"
     end
  
     static.vm.provision "shell", inline: <<-SHELL
     
     	sudo apt-get install -y apache2

     	sudo chmod 775 /var/www/html
     	sudo chown -R root:vagrant /var/www/html

     	sudo cp /vagrant/index.html /var/www/html

    	sudo systemctl enable apache2
     	sudo systemctl start apache2

     SHELL

  end




  config.vm.define "dynamic" do |dynamic|

    dynamic.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"

    dynamic.vm.network "private_network", ip: "192.168.1.81"
     
    dynamic.vm.provider "virtualbox" do |vb|
      vb.name = "01-demosite-php"
      vb.memory = "512"
    end
  
    dynamic.vm.provision "shell", inline: <<-SHELL
     
      sudo apt-get install -y apache2
      sudo apt-get install -y php libapache2-mod-php

      sudo chmod 775 /var/www/html
      sudo chown -R root:vagrant /var/www/html
      
      sudo rm /var/www/html/index.html
      sudo cp /vagrant/index.php /var/www/html

      sudo systemctl enable apache2
      sudo systemctl start apache2

    SHELL

  end

end
