Vagrant.configure("2") do |config|
  config.vm.box = "SergeyPimenov/CentOS8_LAMP"

  config.vm.hostname = "Ansible-VM"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.provision "file", source: "./playbook.yaml", destination: "/vagrant/playbook.yaml"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision :ansible_local do |avm|
    avm.playbook = 'playbook.yaml'
    avm.limit = 'all'
    avm.verbose = true
    avm.install = true
  end
end
